name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # or your project's Node.js version
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint (if configured)
        run: npm run lint
        continue-on-error: true # prevents failure if lint script doesn't exist

      - name: Run tests (if configured)
        run: npm test
        continue-on-error: true # prevents failure if test script doesn't exist

      - name: Build project
        run: npm run build
